import { makeCard } from "./build.ts";

const suit = "cups" as const;
const arcana = "minor" as const;

export const CUPS = [
  makeCard({
    id: "cups-01", name: "Ace of Cups", arcana, suit, rank: 1,
    keywords: ["opening", "feeling", "offer", "well"],
    core: "A feeling has just opened, the way water finds a cup. It is an offer of contact, not a contract and not a soulmate announcement.",
    gift: "You can let a feeling arrive before you draft its future.",
    cost: "An open heart with no rim spills on people who did not ask to be the cup.",
    tilt: "blocked",
    note: "Reversed, the opening is blocked. The feeling is present and cannot be poured. Forcing a speech will not unstop it.",
    motifs: ["a cup overflowing", "water falling into a pool", "a hand offering it"],
    imageCues: [
      "She holds an overflowing gold cup in one hand.",
      "Water pours from the rim and falls into a pool at her feet.",
      "Bookshelves fill the dark room behind her.",
    ],
    teachingLine: "The Ace of Cups is a feeling that has just become available.",
  }),
  makeCard({
    id: "cups-02", name: "Two of Cups", arcana, suit, rank: 2,
    keywords: ["exchange", "mutual", "pledge", "pair"],
    core: "Two people make a real exchange. Both cups are in the picture. The card is mutuality, not a guess about the other person's secret mind.",
    gift: "You can meet someone without managing the whole meeting alone.",
    cost: "A pretty toast can hide the terms you have not said out loud.",
    tilt: "delayed",
    note: "Reversed, the exchange is delayed rather than ruined. Repair is available and not landing. It does not say the other person hates you.",
    motifs: ["two figures each holding a cup", "a small shared token between them", "equal footing"],
    imageCues: [
      "She and a hooded figure stand facing each other, each holding a gold cup.",
      "A small ring hangs in the space between the two cups.",
      "They stand on a stone floor marked by shallow pools of water.",
    ],
    teachingLine: "The Two of Cups is a mutual exchange, not mind-reading.",
  }),
  makeCard({
    id: "cups-03", name: "Three of Cups", arcana, suit, rank: 3,
    keywords: ["friends", "toast", "circle", "joy"],
    core: "Friends raise cups because something was shared and survived. The circle is the point. So is the question of who was not invited.",
    gift: "You can celebrate with the people who were actually there.",
    cost: "A closed circle can call itself warmth while someone stands outside it.",
    tilt: "excess",
    note: "Reversed, the party is overdone or exclusive. Gossip, leftover drink, and a friendship performed for the room rather than lived in it.",
    motifs: ["three people lifting cups", "a shared table", "one empty place at the edge"],
    imageCues: [
      "She and two hooded figures raise gold cups over a wooden table.",
      "One gold cup sits on the table and is not lifted.",
      "Pale vapor rises from the lifted cups.",
    ],
    teachingLine: "The Three of Cups is shared joy, including who gets left out.",
  }),
  makeCard({
    id: "cups-04", name: "Four of Cups", arcana, suit, rank: 4,
    keywords: ["boredom", "refusal", "offer", "apathy"],
    core: "Three cups are already yours, and a fourth is being offered while you look elsewhere. The dissatisfaction may be honest. It may also be a habit of not taking what is extended.",
    gift: "You can notice that an offer is in the room before you dismiss the day.",
    cost: "Contempt for what you have will not produce a more interesting life by itself.",
    tilt: "inward",
    note: "Reversed, the sulk turns inward and finally sees the offered cup, or it deepens until no offer can get your eyes up. The cup was not imaginary.",
    motifs: ["a seated figure ignoring a cup", "three cups already set down", "an offered cup at the edge of sight"],
    imageCues: [
      "She sits looking away from a hand that offers a gold cup at the edge.",
      "Three gold cups are already set down in front of her.",
      "Water covers the floor behind the seat.",
    ],
    teachingLine: "The Four of Cups is boredom in front of something already offered.",
  }),
  makeCard({
    id: "cups-05", name: "Five of Cups", arcana, suit, rank: 5,
    keywords: ["grief", "spill", "remain", "loss"],
    core: "Grief is looking at what spilled. Two cups are still standing behind the mourner. The card does not rush the mourning, and it does not pretend the standing cups are nothing.",
    gift: "You can grieve a real loss without being ordered to look on the bright side.",
    cost: "A stare that will not turn will miss the help still upright.",
    tilt: "inward",
    note: "Reversed, the grief turns, slowly, toward what remains, or it sinks further inward and refuses the two cups still standing. Neither move erases the spill.",
    motifs: ["a cloaked figure facing spilled cups", "two upright cups behind them", "a bridge in the distance"],
    imageCues: [
      "Three gold cups lie tipped over, spilling water onto wet stone.",
      "Two upright gold cups stand full beside her.",
      "A stone bridge crosses moonlit water behind her while she looks back over her shoulder.",
    ],
    teachingLine: "The Five of Cups is grief that can miss what is still standing.",
  }),
  makeCard({
    id: "cups-06", name: "Six of Cups", arcana, suit, rank: 6,
    keywords: ["memory", "kindness", "past", "gift"],
    core: "A kindness moves between people, often with the past in the cup. Memory can be a gift. It can also be a room you furnish so you never have to live in this year.",
    gift: "You can offer a simple kindness without a ledger.",
    cost: "Nostalgia can be used to avoid the adult in front of you.",
    tilt: "inward",
    note: "Reversed, the memory turns inward and edits the past into a softer country. The flower in the cup is not a time machine.",
    motifs: ["a cup filled with flowers passed between two people", "a courtyard", "one figure offering and one receiving"],
    imageCues: [
      "She offers a gold cup filled with pale flowers.",
      "A hooded figure reaches to take the cup.",
      "They stand beside a stone courtyard basin of water.",
    ],
    teachingLine: "The Six of Cups is a kindness that carries memory with it.",
  }),
  makeCard({
    id: "cups-07", name: "Seven of Cups", arcana, suit, rank: 7,
    keywords: ["options", "fantasy", "glitter", "choice"],
    core: "Too many attractive feelings are in the air, each in its own cup. Imagination is working. A choice has not been made, and the glittering ones are not all drinkable.",
    gift: "You can enjoy a vision long enough to ask which cup has a bottom.",
    cost: "Collecting possibilities is a way to never pick up a single real one.",
    tilt: "excess",
    note: "Reversed, the fantasy is overdone and starts to thin. Some cups were costume jewelry. Waking from them is a loss and a relief.",
    motifs: ["seven floating cups", "strange tempting shapes rising from them", "a figure looking up"],
    imageCues: [
      "She looks up at a row of seven gold cups.",
      "A fish, a lantern, a mask, a rose, a ship, a key, and a snake rise from the cups.",
      "Dark bookshelves fill the wall behind her.",
    ],
    teachingLine: "The Seven of Cups is too many attractive feelings and no choice yet.",
  }),
  makeCard({
    id: "cups-08", name: "Eight of Cups", arcana, suit, rank: 8,
    keywords: ["leaving", "enough", "walk", "unsatisfied"],
    core: "You walk away from a setup that looks full because it is not enough. The leaving is not a tantrum. It is a measured disappointment.",
    gift: "You can exit a life that photographs well and still feels vacant.",
    cost: "Leaving can become a style, used before you have said what was missing.",
    tilt: "delayed",
    note: "Reversed, the walk is delayed. You know the cups are not enough and you are still in the room, packing nothing. Or you return before you have learned why you left.",
    motifs: ["a figure walking toward mountains", "eight cups stacked and left behind", "a moon over the path"],
    imageCues: [
      "She walks away along a dirt path toward dark mountains.",
      "Eight gold cups are stacked in a pyramid on the path behind her.",
      "A full moon hangs over the path, and a river runs beside it.",
    ],
    teachingLine: "The Eight of Cups walks away from a full table that is not enough.",
  }),
  makeCard({
    id: "cups-09", name: "Nine of Cups", arcana, suit, rank: 9,
    keywords: ["satisfaction", "private", "wish", "content"],
    core: "A private satisfaction is honestly had. The wish, for the moment, fits. Smugness is the shadow sitting on the same bench, not a separate card.",
    gift: "You can enjoy a wish fulfilled without apologizing for the enjoyment.",
    cost: "Contentment performed at other people becomes a fence.",
    tilt: "excess",
    note: "Reversed, satisfaction is overdone and turns greedy, or it feels false in the mouth. The cups on the shelf do not prove you are fine.",
    motifs: ["a figure seated before a row of cups", "arms loosely open", "a full shelf"],
    imageCues: [
      "She sits in a chair with her arms resting open on the arms.",
      "A row of gold cups stands on the shelf above her head.",
      "Books fill the shelves around the cups.",
    ],
    teachingLine: "The Nine of Cups is private satisfaction, with smugness nearby.",
  }),
  makeCard({
    id: "cups-10", name: "Ten of Cups", arcana, suit, rank: 10,
    keywords: ["household", "warmth", "bond", "home"],
    core: "A household is warm in this picture. Children, partners, friends, or a chosen family stand under a shared sky. The card is a felt home. It is not a promise the feeling lasts forever.",
    gift: "You can recognize belonging when it is actually happening.",
    cost: "A perfect picture of family can shame the house you really have.",
    tilt: "delayed",
    note: "Reversed, the warmth is delayed or cracked. The wish for home is not a lie. The picture and the kitchen are not currently the same place.",
    motifs: ["a small group under a rainbow arc of cups", "a house behind them", "linked hands"],
    imageCues: [
      "Gold cups form an arc over a colored rainbow.",
      "A house with lit windows stands behind the group.",
      "She holds the hand of a hooded figure while other hooded figures stand beside them.",
    ],
    teachingLine: "The Ten of Cups is household warmth, not a guarantee.",
  }),
  makeCard({
    id: "cups-page", name: "Page of Cups", arcana, suit, rank: "page",
    keywords: ["tender", "surprise", "student", "feeling"],
    core: "This mode is learning to take a feeling seriously, including the odd ones. A fish in a cup is a surprise, not a career plan.",
    gift: "You can listen to a shy feeling without mocking it or marrying it.",
    cost: "Every whim treated as a message from destiny will exhaust the people around you.",
    tilt: "inward",
    note: "Reversed, the sensitivity turns inward and becomes sulking, or a creative impulse is dismissed as silly before it can be tried. The fish was only asking to be noticed.",
    motifs: ["a youthful figure looking into a cup", "a small fish rising from the cup", "soft water behind"],
    imageCues: [
      "She leans over a stone basin and looks down into a gold cup.",
      "A small silver fish rises out of the cup.",
      "She holds a thin tool near the fish while the cup floats in the basin.",
    ],
    teachingLine: "The Page of Cups learns by taking a feeling seriously.",
  }),
  makeCard({
    id: "cups-knight", name: "Knight of Cups", arcana, suit, rank: "knight",
    keywords: ["offer", "ideal", "pursuit", "proposal"],
    core: "This mode pursues a feeling or carries an offer toward someone. Idealism is in the saddle. So is the risk of proposing a poem when the moment needed a plan.",
    gift: "You can make an offer that is actually about the other person.",
    cost: "A beautiful approach can avoid the practical question sitting in the road.",
    tilt: "delayed",
    note: "Reversed, the offer is delayed, moody, or jealous of its own dream. The cup is still extended. The follow-through is not.",
    motifs: ["a rider holding a cup as if it might spill", "a slow horse", "water in the distance"],
    imageCues: [
      "She rides a dark horse along a moonlit shore.",
      "She holds a gold cup while droplets spray from its rim.",
      "A small white dog runs beside the horse, and water stretches behind them.",
    ],
    teachingLine: "The Knight of Cups pursues a feeling, idealism included.",
  }),
  makeCard({
    id: "cups-queen", name: "Queen of Cups", arcana, suit, rank: "queen",
    keywords: ["depth", "empathy", "inhabit", "boundary"],
    core: "This mode inhabits emotional depth without putting it on a stage. Empathy here has a shore. It is not an obligation to drown for company.",
    gift: "You can feel with someone and still know where you end.",
    cost: "Absorbing every mood in the room will empty the cup you came in with.",
    tilt: "inward",
    note: "Reversed, depth turns inward and becomes moodiness, or caretaking with no edge. Feeling everything is not the same as understanding it.",
    motifs: ["a seated figure with a closed ornate cup", "water at her feet", "a still face"],
    imageCues: [
      "She sits in still water that reaches her legs.",
      "She holds a closed gold cup with a lid in both hands.",
      "A moonlit library waterway stretches behind her.",
    ],
    teachingLine: "The Queen of Cups inhabits feeling without performing it.",
  }),
  makeCard({
    id: "cups-king", name: "King of Cups", arcana, suit, rank: "king",
    keywords: ["steady", "feeling", "direct", "calm"],
    core: "This mode directs feeling so other people can rely on it. The sea is moving. The seat does not pretend the sea is gone.",
    gift: "You can stay kind and clear while the feeling is strong.",
    cost: "Calm used as a lid will make the room afraid to bring you the truth.",
    tilt: "blocked",
    note: "Reversed, the steadiness is blocked. Feeling either floods the chair or is locked so tightly that nobody can get a true answer. Control is not the same as care.",
    motifs: ["a throne set in moving water", "a cup held level", "a ship or fish in the background"],
    imageCues: [
      "She sits on a stone throne set in moving waves.",
      "She holds a gold cup level in one hand.",
      "A sailing ship and a leaping fish appear in the water behind her.",
    ],
    teachingLine: "The King of Cups directs feeling so it can be relied on.",
  }),
];
