import { makeCard } from "./build.ts";

export const MAJORS = [
  makeCard({
    id: "major-00",
    name: "The Fool",
    arcana: "major",
    suit: null,
    rank: 0,
    keywords: ["beginning", "edge", "company", "step"],
    core: "The Fool is the moment a beginning is still a choice. The cliff is visible, and nothing in the picture has talked the step out of existing.",
    gift: "You can start without a finished map, and the start still counts.",
    cost: "A beginning taken only to look brave leaves the practical kit behind.",
    tilt: "delayed",
    note: "Reversed, the step is delayed rather than forbidden. The edge is still there. What stalls is putting weight forward.",
    motifs: ["cliff edge", "bundle on a staff", "small white dog"],
    teachingLine: "The Fool is a beginning you can still refuse.",
    imageCues: [
      "She stands at the edge of a pale cliff, both boots on the rock, the drop in front of her.",
      "A cloth bundle hangs from a staff across her shoulder.",
      "A small white dog stands at her heel, looking up.",
    ],
  }),
  makeCard({
    id: "major-01",
    name: "The Magician",
    arcana: "major",
    suit: null,
    rank: 1,
    keywords: ["tools", "focus", "will", "skill"],
    core: "The Magician is attention gathered around tools that are already on the table. One hand up and one hand down says the idea has to meet the work.",
    gift: "You can use what is actually in reach instead of waiting for a better kit.",
    cost: "Skill used to impress will spend the tools on the performance.",
    tilt: "blocked",
    note: "Reversed, the tools are on the table and the circuit between them is blocked. Wanting the result is not the same as touching the work.",
    motifs: ["four tools on a table", "one hand up and one down", "a gold loop overhead"],
    teachingLine: "The Magician is will that has to pass through real tools.",
    imageCues: [
      "She stands at a wooden table that holds a cup, a blade, a coin, and a wand.",
      "One hand points upward and the other points toward the floor.",
      "A thin gold loop hangs in the air above the table.",
    ],
  }),
  makeCard({
    id: "major-02",
    name: "The High Priestess",
    arcana: "major",
    suit: null,
    rank: 2,
    keywords: ["withheld", "stillness", "study", "threshold"],
    core: "The High Priestess keeps a book closed until the question is specific. Stillness here is not emptiness. It is a refusal to narrate what has not been looked at.",
    gift: "You can wait for the fact you do not have yet, without filling the gap with a guess.",
    cost: "Withheld knowledge can become a private throne.",
    tilt: "inward",
    note: "Reversed, the silence turns inward and stops informing anyone, including you. The book is not missing. It is being used as a wall.",
    motifs: ["two contrasting pillars", "a closed book", "a crescent and pomegranates"],
    teachingLine: "The High Priestess is knowledge that has not agreed to perform.",
    imageCues: [
      "She sits between a black pillar and a pale pillar.",
      "A closed book rests on her lap.",
      "A crescent is set into the floor, and a veil patterned with pomegranates hangs behind her.",
    ],
  }),
  makeCard({
    id: "major-03",
    name: "The Empress",
    arcana: "major",
    suit: null,
    rank: 3,
    keywords: ["making", "body", "care", "abundance"],
    core: "The Empress is fertile making: a body, a field, a thing that grows because it is fed. Care is part of the method, not a mood added later.",
    gift: "You can feed a project, a place, or a person without calling the feeding weakness.",
    cost: "Abundance that cannot say no will be eaten down to the stalk.",
    tilt: "excess",
    note: "Reversed, the care is overdone or choked. Growth is not absent. It is smothered by too much handling, or starved because the feast is only pictured.",
    motifs: ["wheat and a stream", "star pins", "a round cushion"],
    teachingLine: "The Empress is making that depends on feeding.",
    imageCues: [
      "She sits among tall wheat, with a stream behind the grain.",
      "Star-shaped pins catch the light in her hair.",
      "One hand rests on a round cushion marked with a circle, under a green cloak.",
    ],
  }),
  makeCard({
    id: "major-04",
    name: "The Emperor",
    arcana: "major",
    suit: null,
    rank: 4,
    keywords: ["structure", "borders", "duty", "order"],
    core: "The Emperor builds a border and then has to live with what the border protects. Authority here is a job: name the rule, keep it, and do not pretend the mountains are yours.",
    gift: "You can make a structure other people can lean on.",
    cost: "A rule kept after it has gone stale becomes a small kingdom of no.",
    tilt: "blocked",
    note: "Reversed, the structure is blocked or brittle. Either the border is missing and everything spills, or the throne will not hear a fact that arrived after the rule.",
    motifs: ["a ram-carved throne", "a sphere and a scepter", "bare mountains"],
    teachingLine: "The Emperor is responsibility with a border.",
    imageCues: [
      "She sits armored on a stone throne carved with ram heads.",
      "One hand holds a small sphere and the other a long scepter.",
      "Bare mountains stand behind her under a red dusk.",
    ],
  }),
  makeCard({
    id: "major-05",
    name: "The Hierophant",
    arcana: "major",
    suit: null,
    rank: 5,
    keywords: ["teaching", "tradition", "keys", "institution"],
    core: "The Hierophant passes on a way of doing things that already exists. The gift is a key. The risk is borrowing authority you have not tested.",
    gift: "You can learn a craft from people who have already broken it in.",
    cost: "A received rule can be worn as if it were your own mind.",
    tilt: "inward",
    note: "Reversed, the teaching turns inward and either rejects every key or clutches one teacher's voice as the only lock. Tradition is not the enemy. Unexamined obedience is.",
    motifs: ["two students", "keys and a crown", "a teaching hand"],
    teachingLine: "The Hierophant is a taught tradition, including the risk of borrowing it.",
    imageCues: [
      "Two students sit lower than her in a stone archive.",
      "Two keys hang at her belt, and a three-tier crown is on her head.",
      "One hand is raised in a teaching gesture.",
    ],
  }),
  makeCard({
    id: "major-06",
    name: "The Lovers",
    arcana: "major",
    suit: null,
    rank: 6,
    keywords: ["choice", "bond", "fork", "values"],
    core: "The Lovers is a choice that defines a bond, not a guarantee that romance will tidy the choice. The path splits. Someone waits down one of them. You still have to pick.",
    gift: "You can choose with your values in the room instead of choosing by drift.",
    cost: "Calling every attraction a destiny keeps you from naming the fork.",
    tilt: "delayed",
    note: "Reversed, the choice is delayed at the fork. The second figure and the split path are still there. What fails is the decision, not the existence of love.",
    motifs: ["a forked path", "a second figure", "an apple tree"],
    teachingLine: "The Lovers is a choice that will shape a bond.",
    imageCues: [
      "She stands where a garden path splits.",
      "A second adult waits farther along one path, and a small winged light hangs in the sky.",
      "An apple tree grows beside the fork.",
    ],
  }),
  makeCard({
    id: "major-07",
    name: "The Chariot",
    arcana: "major",
    suit: null,
    rank: 7,
    keywords: ["direction", "will", "opposites", "momentum"],
    core: "The Chariot moves because two unlike pulls are aimed at one gate. Will does not delete the opposition. It gives the opposition a road.",
    gift: "You can steer when two parts of you, or two people, do not agree.",
    cost: "Victory that needs both beasts exhausted is a short campaign.",
    tilt: "blocked",
    note: "Reversed, the chariot is blocked. The beasts pull apart, or the rider grips so hard that nothing moves. Direction has not been earned by force alone.",
    motifs: ["a chariot and two beasts", "a starry canopy", "city walls"],
    teachingLine: "The Chariot is will aimed through opposing pulls.",
    imageCues: [
      "She stands in an open chariot without holding reins.",
      "A black beast and a pale beast draw it beneath a starry canopy.",
      "Armor shows at her collar, and a walled city sits behind her.",
    ],
  }),
  makeCard({
    id: "major-08",
    name: "Strength",
    arcana: "major",
    suit: null,
    rank: 8,
    keywords: ["nerve", "patience", "lion", "contact"],
    core: "Strength is nerve that does not need a blow. The lion is met with a hand, not a weapon, and the meeting is the proof.",
    gift: "You can stay with something fierce without making a spectacle of control.",
    cost: "Endless patience can become a way to avoid a necessary no.",
    tilt: "inward",
    note: "Reversed, the nerve turns inward and either collapses into fear or hardens into a private clench. The lion is not the villain. The lost contact is.",
    motifs: ["a hand on a lion", "a gold loop in the hair", "flowers at the feet"],
    teachingLine: "Strength is quiet nerve, not force.",
    imageCues: [
      "She rests one hand on a lion's muzzle and does not strike it.",
      "A gold loop is worked into her hair.",
      "Flowers grow around her feet.",
    ],
  }),
  makeCard({
    id: "major-09",
    name: "The Hermit",
    arcana: "major",
    suit: null,
    rank: 9,
    keywords: ["lamp", "solitude", "search", "counsel"],
    core: "The Hermit carries a small light away from the crowd so the next steps can be seen. Solitude is the method. It is not a personality prize.",
    gift: "You can step back far enough to tell a real question from noise.",
    cost: "A lamp kept only for yourself stops being counsel and becomes exile.",
    tilt: "inward",
    note: "Reversed, the retreat turns inward and loses the path. Isolation is no longer helping you see. It is the place you hide the lantern.",
    motifs: ["a lantern", "a high night path", "a staff"],
    teachingLine: "The Hermit is a lamp carried apart from the crowd.",
    imageCues: [
      "She stands alone on a high night path.",
      "A lantern in one hand lights only the next steps, and a staff is in the other.",
      "The valley below her is dark.",
    ],
  }),
  makeCard({
    id: "major-10",
    name: "Wheel of Fortune",
    arcana: "major",
    suit: null,
    rank: 10,
    keywords: ["turn", "cycle", "change", "luck"],
    core: "The Wheel is a turn you do not fully steer. Seasons, markets, bodies, and rooms change position. Your part is to notice which way it is moving.",
    gift: "You can meet a turn without claiming you caused the whole sky.",
    cost: "Blaming the wheel for every choice keeps your hands off the rim.",
    tilt: "delayed",
    note: "Reversed, the turn is delayed or you are clinging to the position that already passed. The wheel has not stopped being a wheel. You have stopped moving with it.",
    motifs: ["a large wooden wheel", "a hand on the rim", "four surrounding figures"],
    teachingLine: "The Wheel is a turn you do not fully control.",
    imageCues: [
      "A large wooden wheel fills a stone court, and her hand rests on the rim.",
      "Figures of a lion, a bird, a bull, and a person surround the wheel.",
    ],
  }),
  makeCard({
    id: "major-11",
    name: "Justice",
    arcana: "major",
    suit: null,
    rank: 11,
    keywords: ["consequence", "balance", "account", "truth"],
    core: "Justice matches consequence to the act, with the eyes open. It is not revenge, and it is not a mood about fairness. It is the account.",
    gift: "You can look at what was done and what it cost, in the same glance.",
    cost: "A verdict loved more than the facts will cut the wrong thing.",
    tilt: "blocked",
    note: "Reversed, the account is blocked: facts withheld, a scale tipped on purpose, or a consequence that never arrives. The sword does not become kindness by being ignored.",
    motifs: ["scales", "a sword point down", "open eyes between pillars"],
    teachingLine: "Justice is consequence matched to the act.",
    imageCues: [
      "She sits between two pillars with her eyes open.",
      "One hand holds a balanced pair of scales.",
      "The other holds a sword pointed down.",
    ],
  }),
  makeCard({
    id: "major-12",
    name: "The Hanged Man",
    arcana: "major",
    suit: null,
    rank: 12,
    keywords: ["pause", "view", "surrender", "wait"],
    core: "The Hanged Man stops on purpose so the view can change. The hang is voluntary. Insight here is the price of not rushing the old plan.",
    gift: "You can pause a move that would only repeat last month.",
    cost: "A pause with no end date becomes a way to avoid the ground.",
    tilt: "delayed",
    note: "Reversed, the useful pause is delayed or stuck. You are upside down without consent, or you refuse the halt that would have taught you something.",
    motifs: ["hung by one ankle", "a crossed leg", "a tree and a gold ring of light"],
    teachingLine: "The Hanged Man is a voluntary pause that changes the view.",
    imageCues: [
      "She hangs upside down by one ankle from a living tree.",
      "The other leg is crossed, and her face is calm.",
      "A gold ring of light sits behind her head.",
    ],
  }),
  makeCard({
    id: "major-13",
    name: "Death",
    arcana: "major",
    suit: null,
    rank: 13,
    keywords: ["ending", "clearing", "change", "threshold"],
    core: "Death is an ending that clears ground. A role, a story, or a way of living has finished, whether or not you have held the funeral. It is not a prediction that someone will die.",
    gift: "You can let a finished thing be finished so something else has soil.",
    cost: "Refusing the ending keeps you loyal to a corpse of a plan.",
    tilt: "blocked",
    note: "Reversed, the ending is blocked. What is over keeps a chair at the table. The change is not cancelled. It is being postponed at a rising cost.",
    motifs: ["a pale horse", "a plain white banner", "a fallen crown and a sunrise"],
    teachingLine: "Death is change that clears ground, not a death notice.",
    imageCues: [
      "She rides a pale horse in dark armor, carrying a plain white banner.",
      "A crown lies on the road beneath a low sunrise.",
      "Two small distant figures stand unhurt, one older and one a child.",
    ],
  }),
  makeCard({
    id: "major-14",
    name: "Temperance",
    arcana: "major",
    suit: null,
    rank: 14,
    keywords: ["mixing", "measure", "patience", "blend"],
    core: "Temperance mixes by degrees. One cup pours into another. Nothing about the card is a dramatic reconciliation scene.",
    gift: "You can change a mixture a little and see what the new proportion does.",
    cost: "Endless moderation can dodge the moment that needed a full yes or no.",
    tilt: "excess",
    note: "Reversed, the mix is overdone or refused. Too much of one cup, or a refusal to blend at all. The middle path is not automatically wise. It is a method.",
    motifs: ["pouring between two cups", "one foot in water", "iris and a mountain path"],
    teachingLine: "Temperance is mixing by degrees.",
    imageCues: [
      "One foot is in a stream while she pours from one cup into another.",
      "Iris flowers grow at the bank.",
      "A path leads from the water toward mountains.",
    ],
  }),
  makeCard({
    id: "major-15",
    name: "The Devil",
    arcana: "major",
    suit: null,
    rank: 15,
    keywords: ["bond", "habit", "chain", "attachment"],
    core: "The Devil is a bond you are participating in. The chain is loose enough to lift. That is the point, and it is not a possession story.",
    gift: "You can name the attachment without giving it a supernatural alibi.",
    cost: "A bond denied will keep collecting rent in private.",
    tilt: "excess",
    note: "Reversed, the attachment is overdone, or the loosening has started and feels like loss. Seeing the loose chain does not mean the habit has already let go.",
    motifs: ["a horned shadow", "a loose chain", "an inverted torch"],
    teachingLine: "The Devil is a bond you could set down and have not.",
    imageCues: [
      "A huge horned shadow looms on the wall behind her.",
      "A loose chain circles her wrist and can slip off.",
      "Two smaller adults wear loose chains of their own, and an inverted torch is fixed to the plinth.",
    ],
  }),
  makeCard({
    id: "major-16",
    name: "The Tower",
    arcana: "major",
    suit: null,
    rank: 16,
    keywords: ["collapse", "shock", "structure", "lightning"],
    core: "The Tower is a structure failing because it could not take the truth that hit it. People are thrown clear. The card is not a promise of disaster, and it is not a punishment.",
    gift: "You can stop rebuilding a story that the facts have already cracked.",
    cost: "Shock can be mistaken for the only honest way to change.",
    tilt: "blocked",
    note: "Reversed, the break is blocked or narrowly avoided, and the cracked structure is still being lived in. The lightning showed you something. Dodging it is not the same as repair.",
    motifs: ["a cracking tower", "lightning", "a crown blown from the roof"],
    teachingLine: "The Tower is a false structure breaking, not a scheduled accident.",
    imageCues: [
      "A stone tower cracks under a lightning strike, with fire in the windows.",
      "A crown is blown off the roof.",
      "She and one other adult are thrown clear in midair.",
    ],
  }),
  makeCard({
    id: "major-17",
    name: "The Star",
    arcana: "major",
    suit: null,
    rank: 17,
    keywords: ["hope", "repair", "water", "honesty"],
    core: "The Star is a small honest hope after wreckage. Water is poured on the ground and back into the pool. The hope is maintenance, not a miracle.",
    gift: "You can do one quiet restorative thing without demanding the whole future.",
    cost: "Hope used as a costume will not refill anything.",
    tilt: "delayed",
    note: "Reversed, the hope is delayed. The pool is still there. What stalls is believing a small repair counts before the sky is impressive again.",
    motifs: ["two jugs by a pool", "stars", "kneeling to pour"],
    teachingLine: "The Star is a small honest hope after something broke.",
    imageCues: [
      "She kneels beside a pool in a pale linen shift.",
      "She pours one jug onto the land and another into the water.",
      "A large star and smaller stars fill the night sky.",
    ],
  }),
  makeCard({
    id: "major-18",
    name: "The Moon",
    arcana: "major",
    suit: null,
    rank: 18,
    keywords: ["uncertainty", "fear", "path", "dream"],
    core: "The Moon is a path walked when the light lies a little. Fear, dream, and uncertain fact share the road. The path is still a path.",
    gift: "You can keep walking while you do not yet know which shape is a trick of the light.",
    cost: "Suspicion can become the only map you trust.",
    tilt: "inward",
    note: "Reversed, the fear turns inward and either names itself at last or runs the whole night. Coming out of the fog is not the same as pretending the fog was never there.",
    motifs: ["a path between towers", "a dog and a wolf", "a moon and a pool"],
    teachingLine: "The Moon is uncertainty with the path still underfoot.",
    imageCues: [
      "She walks a pale path between two towers under a large moon.",
      "A dog and a wolf stand on either side of the path.",
      "A crayfish rises from a pool in the foreground.",
    ],
  }),
  makeCard({
    id: "major-19",
    name: "The Sun",
    arcana: "major",
    suit: null,
    rank: 19,
    keywords: ["vitality", "clarity", "day", "warmth"],
    core: "The Sun is plain vitality and being seen in daylight. The warmth is simple. It does not require a moral attached.",
    gift: "You can let a good, clear day be information, not a trap.",
    cost: "Brightness used to deny every shadow will burn the people who need shade.",
    tilt: "excess",
    note: "Reversed, the vitality is overdone or dimmed. Joy performed at full volume, or a sun you will not step into. Daylight is still the card. The dose is the problem.",
    motifs: ["sunflowers", "a large sun", "a smaller companion and a wall"],
    teachingLine: "The Sun is plain vitality, not a prize for optimism.",
    imageCues: [
      "She walks beside a low wall and a row of sunflowers.",
      "A large sun hangs overhead, and a smaller figure walks with her.",
      "A plain banner hangs nearby, with no mark on it.",
    ],
  }),
  makeCard({
    id: "major-20",
    name: "Judgement",
    arcana: "major",
    suit: null,
    rank: 20,
    keywords: ["call", "answer", "rising", "reckoning"],
    core: "Judgement is a call to answer for the life already lived. People rise because the trumpet asked a question, not because a courtroom of the dead has convened.",
    gift: "You can answer what the last chapter is asking of you now.",
    cost: "A reckoning used to condemn yourself forever is not an answer. It is a refusal to stand up.",
    tilt: "blocked",
    note: "Reversed, the call is blocked or refused. You hear it and stay in the box. Waking is available. It is not automatic.",
    motifs: ["rising from a stone tomb", "a trumpet", "other figures rising"],
    teachingLine: "Judgement is a call to answer for the life you have already lived.",
    imageCues: [
      "She rises from an open stone sarcophagus with her arms open.",
      "A figure in the clouds blows a trumpet.",
      "Other small figures rise in the distance beneath a plain banner.",
    ],
  }),
  makeCard({
    id: "major-21",
    name: "The World",
    arcana: "major",
    suit: null,
    rank: 21,
    keywords: ["completion", "cycle", "dance", "wholeness"],
    core: "The World is a cycle completed, with a larger one available after the wreath. The dance is the integration, not a trophy you nail to a wall.",
    gift: "You can close a chapter and feel the shape of what it made.",
    cost: "Completion clutched as an identity will not let the next cycle start.",
    tilt: "delayed",
    note: "Reversed, the ending is delayed by one unfinished piece, or you refuse to step out of a wreath that has already closed. The dance is there. You are hesitating at the edge of it.",
    motifs: ["an oval wreath", "a dance with a wand", "four corner figures"],
    teachingLine: "The World is a cycle completed, and another one available.",
    imageCues: [
      "She dances inside a large oval wreath, a short wand in one hand.",
      "A scarf moves around her.",
      "Four figures occupy the corners: a person, an eagle, a lion, and a bull.",
    ],
  }),
];
