import { makeCard } from "./build.ts";

const suit = "pentacles" as const;
const arcana = "minor" as const;

export const PENTACLES = [
  makeCard({
    id: "pentacles-01", name: "Ace of Pentacles", arcana, suit, rank: 1,
    keywords: ["chance", "material", "seed", "offer"],
    core: "A material chance is in the hand: a coin, a door, a plot of workable ground. It is a beginning in the world of bodies and things. It is not a financial instruction.",
    gift: "You can treat a real opportunity as real, instead of as a mood.",
    cost: "Grabbing every shiny offer will plant nothing deep enough to live.",
    tilt: "delayed",
    note: "Reversed, the chance is delayed or slips out of the hand. The garden gate is still in the picture. What stalls is taking the practical first step.",
    motifs: ["a hand offering a coin", "a garden gate", "a path into cultivated ground"],
    imageCues: [
      "She stands in an open wooden garden gate and holds a large gold star-disk out in one hand.",
      "A dirt path runs through the gate into rows of cultivated plants.",
      "A crescent moon hangs above the dark garden.",
    ],
    teachingLine: "The Ace of Pentacles is a material chance, not money advice.",
  }),
  makeCard({
    id: "pentacles-02", name: "Two of Pentacles", arcana, suit, rank: 2,
    keywords: ["juggle", "balance", "two duties", "adapt"],
    core: "Two obligations are in the air, and you are still upright. The dance is adaptation. It is not proof you can add a third forever.",
    gift: "You can keep two real duties moving without dropping either today.",
    cost: "Endless juggling can hide the fact that one of the coins is burning your hand.",
    tilt: "excess",
    note: "Reversed, the juggle is overdone and a coin hits the ground. Dropping one duty on purpose is different from pretending both are fine while both fail.",
    motifs: ["a figure juggling two coins", "a looping ribbon", "ships on a rough sea behind"],
    imageCues: [
      "She stands on a rock with both hands raised while two gold star-disks hang in the air beside her.",
      "A looping gold ribbon winds between the disks and around her body.",
      "Two sailing ships pitch on a rough sea behind her.",
    ],
    teachingLine: "The Two of Pentacles is two obligations kept in motion.",
  }),
  makeCard({
    id: "pentacles-03", name: "Three of Pentacles", arcana, suit, rank: 3,
    keywords: ["craft", "collaboration", "skill", "plan"],
    core: "Skilled people work from a shared plan. The apprentice, the maker, and the one who holds the design are in the same room. Credit is part of the craft.",
    gift: "You can bring your piece of the skill and let the other pieces stay visible.",
    cost: "A collaboration that erases who did the work will not get the next cathedral.",
    tilt: "blocked",
    note: "Reversed, the teamwork is blocked by ego, sloppy work, or a plan nobody is actually reading. The arch does not rise because one person wants the plaque.",
    motifs: ["three people consulting a plan", "stonework under construction", "a maker's tools"],
    imageCues: [
      "She stands in a stone workshop between two hooded figures whose faces are hidden.",
      "A mallet, chisels, and a glass jar sit on a wooden bench beside stacked stone.",
      "A large gold star-disk is set into the wall, and more disks lie on the cobbles under an arch.",
    ],
    teachingLine: "The Three of Pentacles is skilled work done with other people.",
  }),
  makeCard({
    id: "pentacles-04", name: "Four of Pentacles", arcana, suit, rank: 4,
    keywords: ["hold", "conserve", "grip", "security"],
    core: "You are holding on. Conservation can be sense. It becomes a lock when the coin on the chest matters more than the street you are standing in.",
    gift: "You can keep what actually needs keeping.",
    cost: "A grip that cannot lend, spend, or share will starve the thing it meant to protect.",
    tilt: "blocked",
    note: "Reversed, the hold either cracks into spending you do not understand, or it tightens until nothing moves. Security is not the same as a closed fist.",
    motifs: ["a figure clutching a coin to the chest", "coins under the feet and on the crown", "a city square"],
    imageCues: [
      "She clutches a large gold star-disk against her chest with both arms.",
      "One gold disk sits under each boot, and another floats just above her head.",
      "She stands alone on stone paving between dark city towers.",
    ],
    teachingLine: "The Four of Pentacles is holding on, and the risk of a lock.",
  }),
  makeCard({
    id: "pentacles-05", name: "Five of Pentacles", arcana, suit, rank: 5,
    keywords: ["exclusion", "cold", "hardship", "door"],
    core: "People are outside in the cold while a lit window keeps its own weather. Hardship and exclusion are both in the card. The light inside is not a moral prize for the people who have it.",
    gift: "You can see the door, whether you are the one outside or the one who could open it.",
    cost: "Shame about needing help will keep you walking past the window.",
    tilt: "inward",
    note: "Reversed, the exclusion turns: help is found, or the isolation is clung to because asking feels worse than the snow. The lit glass was never proof you deserved the cold.",
    motifs: ["two figures in snow passing a lit window", "a church or workshop door", "ragged clothes and a crutch or cane"],
    imageCues: [
      "She walks through falling snow with a wooden staff, her cloak torn and patched.",
      "A hooded companion in ragged clothes walks beside her, face hidden.",
      "They pass a stone workshop whose door is open and whose window burns warm.",
      "Gold star-disks lie in the snow around their feet.",
    ],
    teachingLine: "The Five of Pentacles is cold and exclusion, not a moral verdict.",
  }),
  makeCard({
    id: "pentacles-06", name: "Six of Pentacles", arcana, suit, rank: 6,
    keywords: ["give", "receive", "uneven", "measure"],
    core: "Giving and receiving happen on uneven footing. A scale is in the picture because measure matters. Charity without honesty about power is still power.",
    gift: "You can give, or take, without pretending the amounts are equal.",
    cost: "Generosity used to stay above someone will cost them more than the coin.",
    tilt: "excess",
    note: "Reversed, the giving is overdone, string-bound, or refused. Debt dressed up as kindness is still debt. So is pride that will not take a fair share.",
    motifs: ["a standing figure with a scale", "coins passed to kneeling figures", "uneven height between them"],
    imageCues: [
      "She stands higher than two kneeling hooded figures and holds a balance scale with a gold disk in each pan.",
      "Her other hand offers a short stack of gold star-disks downward toward them.",
      "The hooded figures face away, so the drop in height between her and them is clear.",
    ],
    teachingLine: "The Six of Pentacles is giving and receiving on uneven ground.",
  }),
  makeCard({
    id: "pentacles-07", name: "Seven of Pentacles", arcana, suit, rank: 7,
    keywords: ["wait", "tending", "patience", "assess"],
    core: "Work is already in the ground. The task is to look at it and not dig it up every hour to see if you are a good person. Assessment is not the same as anxiety with a hoe.",
    gift: "You can wait on a thing that grows on a schedule you do not control.",
    cost: "Impatience will harvest a green fruit and call the bitterness fate.",
    tilt: "delayed",
    note: "Reversed, the waiting is delayed by fussing, or the crop is disappointing and you refuse to change the method. The vine is not insulted by a honest look.",
    motifs: ["a figure leaning on a tool", "a vine with seven coins as fruit", "a pause rather than a harvest"],
    imageCues: [
      "She leans on a shovel planted in dark soil and looks toward a twisted vine.",
      "The vine is hung with many gold star-disks among the leaves.",
      "She is paused beside the vine and is not picking the disks.",
    ],
    teachingLine: "The Seven of Pentacles waits on work already planted.",
  }),
  makeCard({
    id: "pentacles-08", name: "Eight of Pentacles", arcana, suit, rank: 8,
    keywords: ["apprentice", "repetition", "craft", "practice"],
    core: "Someone is on the bench, making the same form again. Apprenticeship is repetition with attention. It is not a humiliation, and it is not a shortcut.",
    gift: "You can get better by doing the plain version one more time.",
    cost: "Repetition without looking will stamp the same error into every piece.",
    tilt: "blocked",
    note: "Reversed, the practice is blocked by boredom, sloppiness, or a hunger to skip to mastery. The bench is still the teacher.",
    motifs: ["a worker at a bench", "coins hung in a row as finished pieces", "a tool in the hand"],
    imageCues: [
      "She works at a wooden bench, holding a gold star-disk and touching it with a pointed tool.",
      "A row of finished gold star-disks hangs on the wall above her.",
      "More disks and a small tool rest on the bench beside a lit lantern.",
    ],
    teachingLine: "The Eight of Pentacles is apprenticeship: repetition with attention.",
  }),
  makeCard({
    id: "pentacles-09", name: "Nine of Pentacles", arcana, suit, rank: 9,
    keywords: ["self-sufficient", "comfort", "garden", "fence"],
    core: "Comfort has been built, and a fence is part of how it stays comfortable. Self-sufficiency is an achievement. It is also a border.",
    gift: "You can enjoy a competence you actually earned.",
    cost: "A garden that cannot admit need will be a lonely kind of wealth.",
    tilt: "inward",
    note: "Reversed, the comfort turns inward and becomes isolation, or the appearance of ease covers a debt. The falcon on the glove is trained. It is not a friend by itself.",
    motifs: ["a figure in a walled garden", "a bird on the hand", "ripe vines and a fine coat"],
    imageCues: [
      "She stands in a garden enclosed by a stone wall and an iron fence, a falcon perched on her gloved hand.",
      "Ripe grape clusters hang from vines around the wall.",
      "Gold star-disks are set among the vines and on the ground.",
    ],
    teachingLine: "The Nine of Pentacles is self-sufficient comfort, fence included.",
  }),
  makeCard({
    id: "pentacles-10", name: "Ten of Pentacles", arcana, suit, rank: 10,
    keywords: ["legacy", "household", "long work", "inheritance"],
    core: "A long-built household shows its generations, its dogs, its archway. Legacy here is work compounded. It is not magic, and it is not an order to make a financial decision.",
    gift: "You can see yourself inside a longer story of making and keeping.",
    cost: "A family picture can hide who does the maintenance and who only inherits the pose.",
    tilt: "blocked",
    note: "Reversed, the legacy is blocked: a household fight, a tradition that will not update, or wealth that does not reach the people in the courtyard. The arch is not the same as care.",
    motifs: ["an old arch and several generations", "dogs", "coins set into the stone"],
    imageCues: [
      "She stands beneath an old stone arch with gold star-disks set into the wall beside her.",
      "Three dogs stand at her feet: two dark hounds and a small white dog.",
      "A hooded figure and a smaller figure, both seen from behind, wait in the archway.",
    ],
    teachingLine: "The Ten of Pentacles is a long-built household, not a money spell.",
  }),
  makeCard({
    id: "pentacles-page", name: "Page of Pentacles", arcana, suit, rank: "page",
    keywords: ["study", "practical", "student", "attention"],
    core: "This mode learns a practical skill with the whole attention on the coin, the tool, or the page. Ambition here is studious. It is not a announcement.",
    gift: "You can give one craft your eyes until it starts to answer.",
    cost: "Study that never touches the material will stay a polished theory.",
    tilt: "delayed",
    note: "Reversed, the study is delayed by distraction or by treating the practical as beneath you. The coin does not get more interesting because you stare past it.",
    motifs: ["a youthful figure holding a coin up to study it", "a plowed field", "both feet on the ground"],
    imageCues: [
      "She stands with both boots in a plowed field and holds a gold star-disk up close to study it.",
      "Her other hand holds a small hand tool pointed down toward the soil.",
      "Furrows of turned earth stretch behind her under a full moon.",
    ],
    teachingLine: "The Page of Pentacles learns a practical skill with full attention.",
  }),
  makeCard({
    id: "pentacles-knight", name: "Knight of Pentacles", arcana, suit, rank: "knight",
    keywords: ["reliable", "slow", "duty", "persist"],
    core: "This mode pursues slowly and stays. The horse is stopped more than it charges. Reliability is the speed. Stubbornness is the ditch beside that road.",
    gift: "You can keep a routine until the work is actually done.",
    cost: "Method that cannot change its route will plow the same mistake in a straight line.",
    tilt: "blocked",
    note: "Reversed, the reliability is blocked into stuckness, or the routine is abandoned the first time it bores you. Slow was never the same word as absent.",
    motifs: ["a rider paused on a heavy horse", "a coin held carefully", "plowed fields"],
    imageCues: [
      "She sits still on a heavy black horse that stands among plowed fields.",
      "She holds a gold star-disk up in one gloved hand while the other rests on the reins.",
      "A winding road runs through the fields behind the horse.",
    ],
    teachingLine: "The Knight of Pentacles pursues slowly, almost stubbornly.",
  }),
  makeCard({
    id: "pentacles-queen", name: "Queen of Pentacles", arcana, suit, rank: "queen",
    keywords: ["care", "practical", "body", "place"],
    core: "This mode inhabits care for body, place, and practical need. The garden is not a metaphor you can eat. Someone has to know where the food is.",
    gift: "You can tend what is physical without calling that tending small.",
    cost: "Care that will not accept help becomes another unpaid job with a wreath on it.",
    tilt: "excess",
    note: "Reversed, the caretaking is overdone and the caretaker disappears, or the practical is neglected while the appearance of nurture stays up. A full lap is not a plan for the week.",
    motifs: ["a seated figure with a coin in a lush garden", "a rabbit or goat nearby", "attention on the immediate living thing"],
    imageCues: [
      "She sits in a garden of herbs and flowering plants, holding a gold star-disk in her lap with both hands.",
      "A white rabbit sits beside her knee, and a horned goat stands just behind the rabbit.",
      "The animals are close among the living plants around her.",
    ],
    teachingLine: "The Queen of Pentacles inhabits care for body, place, and need.",
  }),
  makeCard({
    id: "pentacles-king", name: "King of Pentacles", arcana, suit, rank: "king",
    keywords: ["resources", "steward", "direct", "steady"],
    core: "This mode directs resources. Stewardship is the job. Money is not a moral prize, and this card will not tell you what to do with yours.",
    gift: "You can make material decisions that other people can live inside.",
    cost: "Security used as status will measure people by what they produce for the chair.",
    tilt: "excess",
    note: "Reversed, stewardship is overdone into hoarding or show, or it fails and the abundance was a front. A vine carved on a throne does not make the ruler generous.",
    motifs: ["a throne among vines", "a coin on the knee", "a bull or carved bulls at the arms"],
    imageCues: [
      "She sits on a high stone throne wrapped in vines.",
      "A gold star-disk rests against her raised knee on the left arm of the throne.",
      "Carved bull heads with horns face outward from both throne arms.",
    ],
    teachingLine: "The King of Pentacles directs resources without treating money as virtue.",
  }),
];
