import { makeCard } from "./build.ts";

const suit = "swords" as const;
const arcana = "minor" as const;

export const SWORDS = [
  makeCard({
    id: "swords-01", name: "Ace of Swords", arcana, suit, rank: 1,
    keywords: ["truth", "cut", "clarity", "start"],
    core: "A clear cut becomes available: a sentence that is true enough to change the room. The blade is an idea with an edge, not a license to be cruel.",
    gift: "You can say the necessary true thing once, cleanly.",
    cost: "A truth swung for victory will cut the people you still need.",
    tilt: "blocked",
    note: "Reversed, the clarity is blocked or used as a weapon and then regretted. The idea is sharp. The hand is not ready, or it is too ready.",
    motifs: ["a single upright sword", "a crown or wreath at the tip", "clear sky"],
    imageCues: [
      "She holds one steel sword upright beside a library window.",
      "A gold wreath sits at the tip of the blade against a pale sky.",
    ],
    teachingLine: "The Ace of Swords is a necessary truth, not a license to wound.",
  }),
  makeCard({
    id: "swords-02", name: "Two of Swords", arcana, suit, rank: 2,
    keywords: ["truce", "blind", "stalemate", "refusal"],
    core: "Two blades are crossed and the eyes are covered. This is a truce, or a refusal to look. Peace bought by not deciding is still a decision.",
    gift: "You can pause a fight long enough to lower the noise.",
    cost: "A blindfold worn after the facts arrived is avoidance with good posture.",
    tilt: "blocked",
    note: "Reversed, the stalemate breaks badly or the blindfold comes off before you have a way to hold what you see. The sea was never calm just because you refused it.",
    motifs: ["a seated figure with two crossed swords", "a blindfold", "water behind"],
    imageCues: [
      "She sits on a stone bench holding two steel swords crossed in front of her.",
      "A dark mask crosses her eyes.",
      "Moonlit water stretches behind her, with warm light from an open doorway.",
    ],
    teachingLine: "The Two of Swords is a truce that may be a refusal to look.",
  }),
  makeCard({
    id: "swords-03", name: "Three of Swords", arcana, suit, rank: 3,
    keywords: ["sorrow", "words", "hurt", "rain"],
    core: "Hurt has words attached. The pain is real sorrow, not a fate that picked you out of a crowd. Someone said or did the thing, and the weather matches.",
    gift: "You can name the hurt without turning it into a life sentence.",
    cost: "Replaying the sentence keeps the blades in the weather.",
    tilt: "inward",
    note: "Reversed, the sorrow turns inward and either starts to leave the body or gets curated as an identity. Recovery is not the same as pretending the storm was tasteful.",
    motifs: ["a heart pierced by three swords", "rain", "no attacker in frame"],
    imageCues: [
      "She stands in the rain looking at a hanging heart pierced by three steel swords.",
      "Rain falls through a broken window onto the wet floor.",
      "No other person is in the room.",
    ],
    teachingLine: "The Three of Swords is sorrow with words attached, not a curse.",
  }),
  makeCard({
    id: "swords-04", name: "Four of Swords", arcana, suit, rank: 4,
    keywords: ["rest", "recovery", "stillness", "pause"],
    core: "The mind has spent itself, and the card lies down. Rest is the strategy. It is not laziness wearing a church window.",
    gift: "You can stop thinking as a way to let the thinking finish.",
    cost: "Retreat that has no morning attached becomes another kind of exile.",
    tilt: "delayed",
    note: "Reversed, the rest is delayed. You know you are exhausted and you stay upright anyway, or you wake before the repair has happened. The bed was part of the work.",
    motifs: ["a figure lying still", "three swords on the wall and one beneath", "a quiet interior"],
    imageCues: [
      "She lies still with her eyes closed on a wooden bench.",
      "Three steel swords hang on the wall above her.",
      "One steel sword lies on the floor in front of the bench.",
    ],
    teachingLine: "The Four of Swords is rest after mental exhaustion.",
  }),
  makeCard({
    id: "swords-05", name: "Five of Swords", arcana, suit, rank: 5,
    keywords: ["hollow win", "conflict", "score", "walk away"],
    core: "This is a win that leaves the room colder. Swords are collected. People walk off. The scoreboard is not the same thing as a solved problem.",
    gift: "You can notice when you are keeping score before the habit owns the afternoon.",
    cost: "A victory that needs the others diminished will cost the work those people were doing with you.",
    tilt: "excess",
    note: "Reversed, the hollow win is overdone or finally tasted. Spite, or the sourness after it. Putting the swords down does not rewrite the walk-away.",
    motifs: ["one figure holding gathered swords", "two figures leaving", "a cold sky"],
    imageCues: [
      "She holds steel swords in both hands under a pale cold sky.",
      "Two hooded figures walk away with their backs turned.",
    ],
    teachingLine: "The Five of Swords is a win that empties the room.",
  }),
  makeCard({
    id: "swords-06", name: "Six of Swords", arcana, suit, rank: 6,
    keywords: ["passage", "leaving", "water", "aftermath"],
    core: "You leave troubled water in a small boat. The far bank is not a personality transplant. Passage is movement away from the fight, not erasure of it.",
    gift: "You can go somewhere quieter without claiming you are a new person at the dock.",
    cost: "Flight sold as healing will pack the same argument in the baggage.",
    tilt: "delayed",
    note: "Reversed, the passage is delayed. The boat is loaded and still tied, or you discover the water came with you. Leaving the shore was not the whole task.",
    motifs: ["a boat with huddled passengers", "six swords standing in the hull", "a ferryman and a far shore"],
    imageCues: [
      "She stands in a wooden boat holding a pole with a tied sack.",
      "Six steel swords stand upright in the hull.",
      "Two hooded passengers sit with their faces turned away, and lights mark a far shore.",
    ],
    teachingLine: "The Six of Swords is passage out of troubled water, not erasure.",
  }),
  makeCard({
    id: "swords-07", name: "Seven of Swords", arcana, suit, rank: 7,
    keywords: ["stealth", "strategy", "partial", "exit"],
    core: "Someone carries swords away from a camp and does not take all of them. This is strategy, stealth, or a half-honest exit. It is not heroism by default.",
    gift: "You can move a piece of a problem without announcing the whole plan.",
    cost: "Cleverness that hides the important blade will be found out by the people who needed it.",
    tilt: "inward",
    note: "Reversed, the sneak turns inward: self-deception, or a secret that has become too heavy to carry. Getting caught is one ending. Confessing the missing swords is another.",
    motifs: ["a figure tiptoeing with an armful of swords", "a camp left behind", "two swords left stuck in the ground"],
    imageCues: [
      "She steps away from a tent camp carrying a bundle of steel swords.",
      "Two steel swords stand stuck in the ground beside her.",
      "Hooded figures in the camp have their backs turned under a full moon.",
    ],
    teachingLine: "The Seven of Swords is a strategy that hides something.",
  }),
  makeCard({
    id: "swords-08", name: "Eight of Swords", arcana, suit, rank: 8,
    keywords: ["bind", "thought", "trap", "narrow"],
    core: "The bind is made of thoughts more than iron. The ropes are real in the picture, and the way out is not glamorous. It is nearby.",
    gift: "You can question a trap that your own sentences keep tying.",
    cost: "Calling every limit imaginary will not untie a rope that is actually there.",
    tilt: "blocked",
    note: "Reversed, the bind loosens or you refuse to test it. Freedom starts as an undignified step, not as a speech about mindset.",
    motifs: ["a bound and blindfolded figure", "swords planted in a ring", "shallow water and a distant castle"],
    imageCues: [
      "She stands in shallow water wearing a cloth blindfold, with rope binding her wrists.",
      "Steel swords are planted in a ring around her.",
      "A castle stands on the far bank.",
    ],
    teachingLine: "The Eight of Swords is a bind made more of thoughts than of iron.",
  }),
  makeCard({
    id: "swords-09", name: "Nine of Swords", arcana, suit, rank: 9,
    keywords: ["dread", "night", "worry", "wake"],
    core: "The mind is awake at the wrong hour, and the swords are on the wall where a sleeper can count them. Dread is not evidence that every feared thing is already true.",
    gift: "You can name the night thought as a night thought.",
    cost: "Rehearsing the worst until dawn will not make the morning safer.",
    tilt: "inward",
    note: "Reversed, the dread turns, sometimes into speech and sometimes into a deeper spiral. Telling one accurate person is different from believing every 3 a.m. story.",
    motifs: ["a figure sitting up in bed", "head in hands", "nine swords on the dark wall"],
    imageCues: [
      "She sits up in bed and covers her face with both hands.",
      "Nine steel swords hang on the wall in three groups of three.",
      "A lamp is lit on the table beside the bed.",
    ],
    teachingLine: "The Nine of Swords is waking dread, not a confirmed future.",
  }),
  makeCard({
    id: "swords-10", name: "Ten of Swords", arcana, suit, rank: 10,
    keywords: ["ending", "over", "story", "bottom"],
    core: "A story or a belief has gone as far as it can, and the ending is painful and obvious. Ten blades are more than a practical murder. They are an idea finished past usefulness. It is not a prediction of violence.",
    gift: "You can stop negotiating with a narrative that is already on the ground.",
    cost: "Dramatizing the bottom can delay the small get-up that follows it.",
    tilt: "blocked",
    note: "Reversed, the ending is blocked by a refusal to call the story over, or the worst has passed and you are still lying in the pose. Morning is a thin line, not a reward for suffering correctly.",
    motifs: ["a figure face down", "ten swords in the back", "a thin dawn on the horizon"],
    imageCues: [
      "She lies face down on bare ground, her hair covering her face.",
      "Steel swords stand in a row through the back of her coat.",
      "A pale dawn is on the horizon.",
    ],
    teachingLine: "The Ten of Swords is an ending of a story that went too far, not a threat.",
  }),
  makeCard({
    id: "swords-page", name: "Page of Swords", arcana, suit, rank: "page",
    keywords: ["watch", "question", "student", "alert"],
    core: "This mode learns by watching, asking, and not swallowing the first explanation. The wind is up. Curiosity has an edge and has not earned a verdict yet.",
    gift: "You can ask the next question instead of performing certainty.",
    cost: "Questions used as needles will make people hide the useful answer.",
    tilt: "excess",
    note: "Reversed, the watching is overdone: gossip, spying, or a cleverness that will not be taught. Information gathered to feel sharp is not study.",
    motifs: ["a youthful figure with a sword held up to the wind", "clouds moving", "an alert stance"],
    imageCues: [
      "She stands on a stone parapet and raises one plain steel sword into the wind.",
      "Her hair and coat blow while clouds move behind her.",
    ],
    teachingLine: "The Page of Swords learns by asking, not by the first explanation.",
  }),
  makeCard({
    id: "swords-knight", name: "Knight of Swords", arcana, suit, rank: "knight",
    keywords: ["argument", "speed", "charge", "intellect"],
    core: "This mode pursues an argument at speed. The charge can cut through fog. It can also arrive before the facts have their boots on.",
    gift: "You can move a necessary truth quickly when delay would rot it.",
    cost: "Winning the sentence and losing the person is a kind of wreck.",
    tilt: "excess",
    note: "Reversed, the charge is overdone. The horse and the opinion are the same animal. Slowing down is not cowardice. It is how you avoid the ditch.",
    motifs: ["a rider bent into the wind", "a sword thrust forward", "storm clouds"],
    imageCues: [
      "She rides a dark horse and thrusts a steel sword forward.",
      "Her hair streams back under heavy storm clouds.",
    ],
    teachingLine: "The Knight of Swords pursues an argument faster than the room.",
  }),
  makeCard({
    id: "swords-queen", name: "Queen of Swords", arcana, suit, rank: "queen",
    keywords: ["boundary", "clear", "honest", "edge"],
    core: "This mode inhabits a clean boundary. The air is cold enough to see. Direct speech is the care. It is not a punishment, and it is not a woman entering your life.",
    gift: "You can say no, or yes, without a fog of politeness around the blade.",
    cost: "Clarity used to humiliate will empty the chair beside you.",
    tilt: "inward",
    note: "Reversed, the boundary turns inward and becomes bitterness or a cutting joke you will not own. A clean edge is not the same as a grudge with good diction.",
    motifs: ["a seated figure with an upright sword", "one hand open", "clouds and a high seat"],
    imageCues: [
      "She sits on a high stone seat among clouds and holds a steel sword upright.",
      "Her other hand rests open on the stone arm of the seat.",
      "A full moon hangs in the sky behind her.",
    ],
    teachingLine: "The Queen of Swords inhabits a clean boundary. The mode can be you.",
  }),
  makeCard({
    id: "swords-king", name: "King of Swords", arcana, suit, rank: "king",
    keywords: ["judgment", "reason", "direct", "law"],
    core: "This mode directs judgment. Reason is the tool, and cruelty dressed as reason is the failure mode. A ruling is not wise because it sounds cold.",
    gift: "You can decide from the facts you actually have.",
    cost: "Intellect used to stay above the human cost will make a legal-sounding mess.",
    tilt: "blocked",
    note: "Reversed, judgment is blocked by bias, or it becomes harsh because harshness feels like rigor. The sword does not get cleaner by being swung harder.",
    motifs: ["a seated judge with a sword held aside", "butterflies or birds in carved stone", "a stern open gaze"],
    imageCues: [
      "She sits on a stone throne and holds a steel sword down at her side.",
      "Butterflies are carved into the stone around the throne.",
      "She looks straight ahead with a stern, open gaze.",
    ],
    teachingLine: "The King of Swords directs judgment, and can mistake cruelty for reason.",
  }),
];
