import { makeCard } from "./build.ts";

const suit = "wands" as const;
const arcana = "minor" as const;

export const WANDS = [
  makeCard({
    id: "wands-01", name: "Ace of Wands", arcana, suit, rank: 1,
    keywords: ["spark", "will", "start", "heat"],
    core: "A live start sits in the hand before it has a schedule. The heat is real, and it wants one direction rather than a speech about potential.",
    gift: "You can begin the piece of work while the heat is still honest.",
    cost: "Heat with nowhere to go opens three efforts and finishes none of them.",
    tilt: "excess",
    note: "Reversed, the spark is too much for the container you have. The urge has not died. It spills, and every spill gets introduced as a new project.",
    motifs: ["a sprouting wand in one hand", "bare ground", "a small flare of fire"],
    imageCues: [
      "She stands on bare dark ground holding one leafy wand.",
      "A small flame burns at the tip of the wand.",
      "The ground around her is empty.",
    ],
    teachingLine: "The Ace of Wands is a start that still needs a single direction.",
  }),
  makeCard({
    id: "wands-02", name: "Two of Wands", arcana, suit, rank: 2,
    keywords: ["plan", "horizon", "distance", "hold"],
    core: "You can see past the first step, and the seeing has become its own room. One wand is planted where you stand. The other is a question about how far the work should travel.",
    gift: "A plan that looks at the actual distance beats a mood about ambition.",
    cost: "The balcony can become the place you live instead of the place you leave.",
    tilt: "delayed",
    note: "Reversed, the horizon stays visible and the departure does not happen. The map is not what failed. The date you keep not choosing is.",
    motifs: ["a figure on a balcony", "one planted wand and one held wand", "a far shore"],
    imageCues: [
      "She stands on a stone balcony holding one wand.",
      "A second wand is planted upright beside her at the railing.",
      "Dark water and a distant shore lie beyond the balcony.",
    ],
    teachingLine: "The Two of Wands is a plan looking across a real distance.",
  }),
  makeCard({
    id: "wands-03", name: "Three of Wands", arcana, suit, rank: 3,
    keywords: ["sent", "waiting", "return", "venture"],
    core: "Something you sent is already away from your hands. The work now is to watch for the return without pretending you still hold the oars.",
    gift: "You can let a finished send-off stay sent.",
    cost: "Checking the water every hour steals the next piece of making.",
    tilt: "inward",
    note: "Reversed, the waiting turns into a private scoreboard. The outgoing work is being asked to report your worth, which is not its job.",
    motifs: ["a figure watching water", "ships or birds far off", "a staff planted on a bluff"],
    imageCues: [
      "She stands on a rocky bluff above the water, holding a tall staff whose end rests on the stone.",
      "Sailing ships sit far out on the water.",
      "Birds fly in the sky beside her.",
    ],
    teachingLine: "The Three of Wands is work already sent, and the wait that follows.",
  }),
  makeCard({
    id: "wands-04", name: "Four of Wands", arcana, suit, rank: 4,
    keywords: ["shelter", "milestone", "gathering", "pause"],
    core: "A shelter is standing. People can be under it for a while without turning the gathering into the entire project.",
    gift: "You can mark that a stage is actually up, not merely hoped for.",
    cost: "A celebration that refuses to end starts lying about the work being finished.",
    tilt: "excess",
    note: "Reversed, the festivity is overdone or cannot be entered. The posts of the shelter are there. What fails is letting the moment be only a moment.",
    motifs: ["four upright wands as a canopy", "a gathered threshold", "garlands without lettering"],
    imageCues: [
      "She stands on a raised stone step under a canopy of upright wooden posts.",
      "Flower garlands wrap the posts and the crossbeam.",
      "Hooded figures wait in the shadows behind the posts.",
    ],
    teachingLine: "The Four of Wands is a pause under something you have already built.",
  }),
  makeCard({
    id: "wands-05", name: "Five of Wands", arcana, suit, rank: 5,
    keywords: ["clash", "competition", "noise", "unsorted"],
    core: "Several wills hit the same small space, and nobody has agreed who referees. The noise is information about desire. It is not yet a reason to burn the work.",
    gift: "You can treat the scuffle as a map of what people actually want.",
    cost: "If every bump must be won, the thing being built never gets a shape.",
    tilt: "blocked",
    note: "Reversed, the clash is blocked into resentment or fake harmony. The sticks are still in the room. People have only stopped admitting they are swinging them.",
    motifs: ["several people with staves crossing", "no referee", "uneven ground"],
    imageCues: [
      "She stands on uneven ground gripping wooden staves.",
      "Hooded figures around her swing staves that cross hers.",
      "No one stands apart as a referee.",
    ],
    teachingLine: "The Five of Wands is messy competition without a referee.",
  }),
  makeCard({
    id: "wands-06", name: "Six of Wands", arcana, suit, rank: 6,
    keywords: ["recognition", "return", "credit", "visible"],
    core: "Effort has been seen in public. Being seen is not the same event as the work, and both can be true in the same afternoon.",
    gift: "You can take the credit that belongs to the effort without shrinking it to be polite.",
    cost: "A parade starts to matter more than the next unglamorous step.",
    tilt: "excess",
    note: "Reversed, recognition is overdone, or it curdles because it did not come in the costume you wanted. The ride through the gate is not the craft.",
    motifs: ["a rider welcomed through a gate", "a raised wand", "onlookers"],
    imageCues: [
      "She rides a dark horse through a stone gate.",
      "One wand is raised in her hand.",
      "Hooded onlookers stand on either side of the gate.",
    ],
    teachingLine: "The Six of Wands is public recognition after effort.",
  }),
  makeCard({
    id: "wands-07", name: "Seven of Wands", arcana, suit, rank: 7,
    keywords: ["defense", "high ground", "pressure", "stand"],
    core: "You are holding a position while other claims push up from below. The high ground may be legitimate. The fatigue of defending it is also part of the card.",
    gift: "You can keep the part of the stance that is still true.",
    cost: "Defense can become the whole personality and abandon the original aim.",
    tilt: "blocked",
    note: "Reversed, the stand is blocked by exhaustion or by a hill that was never yours. Coming down is not always defeat. Sometimes the test is over.",
    motifs: ["one figure above", "staves reaching up from below", "a steep footing"],
    imageCues: [
      "She stands on a high steep rock holding a staff.",
      "Hooded figures below lift wooden staves up toward her.",
      "She is above them on the narrow footing.",
    ],
    teachingLine: "The Seven of Wands is a defended position and the cost of holding it.",
  }),
  makeCard({
    id: "wands-08", name: "Eight of Wands", arcana, suit, rank: 8,
    keywords: ["motion", "news", "speed", "air"],
    core: "Messages, travel, or a decision are already moving. The open question is no longer whether motion will happen. It is happening.",
    gift: "You can clear space for something that is about to land.",
    cost: "Speed makes a sloppy arrival look like destiny.",
    tilt: "delayed",
    note: "Reversed, the flight stalls. Mail, travel, or the yes you were counting on hangs in the air and does not come down. The stall is the news.",
    motifs: ["wands crossing open sky", "no figure required to be the center", "a sense of swift approach"],
    imageCues: [
      "She stands at the bottom of an open night sky.",
      "Wooden wands streak diagonally overhead, trailing light.",
      "The wands are already in flight above her.",
    ],
    teachingLine: "The Eight of Wands is motion that has already left the hand.",
  }),
  makeCard({
    id: "wands-09", name: "Nine of Wands", arcana, suit, rank: 9,
    keywords: ["guard", "fatigue", "wound", "last"],
    core: "You are still upright, and you are tired of being upright. The guard post made sense when the threat was fresh. It may now be the entire job.",
    gift: "You can tell a real threat from the habit of bracing.",
    cost: "A wound that never clocks out will not let help through the door.",
    tilt: "inward",
    note: "Reversed, the vigilance turns inward and watches you more than the gate. Rest is being treated as danger. The bandage is not a personality.",
    motifs: ["a weary figure with a bandaged head", "eight wands as a fence", "one wand held ready"],
    imageCues: [
      "A cloth bandage wraps her forehead.",
      "She holds one wand ready in both hands.",
      "A fence of upright wooden stakes stands behind her.",
    ],
    teachingLine: "The Nine of Wands is guarding what has already worn you down.",
  }),
  makeCard({
    id: "wands-10", name: "Ten of Wands", arcana, suit, rank: 10,
    keywords: ["burden", "completion", "load", "overreach"],
    core: "The bundle is real, and carrying all of it has become the proof that you are working. The gate is close. So is the point where the wood is simply too much.",
    gift: "You can set down the sticks that are not yours to take through the last gate.",
    cost: "Hauling everything is a way to avoid saying which part matters.",
    tilt: "excess",
    note: "Reversed, the overload tips. The bundle scatters, or you refuse to admit it was never one person's job. Completion does not require martyrdom.",
    motifs: ["a figure bent under ten wands", "a town gate ahead", "the load hiding the face"],
    imageCues: [
      "She walks a path with a heavy bundle of wooden staves across her shoulders.",
      "She grips the ropes that hold the load.",
      "A stone gate stands ahead on the path.",
    ],
    teachingLine: "The Ten of Wands is a load that has become the whole job.",
  }),
  makeCard({
    id: "wands-page", name: "Page of Wands", arcana, suit, rank: "page",
    keywords: ["experiment", "curiosity", "student", "spark"],
    core: "This is learning by trying one brave, small experiment. Curiosity has heat. It has not promised anyone a vocation.",
    gift: "You can run a test without making the test your name.",
    cost: "A first try that demands applause will not sit still long enough to teach you.",
    tilt: "delayed",
    note: "Reversed, the experiment is delayed by self-consciousness. The spark is in the hand. What stalls is letting it be amateur in public.",
    motifs: ["a young stance holding a sprouting wand", "looking at the wand rather than a crowd", "open ground"],
    imageCues: [
      "She stands on open bare ground.",
      "She holds a small leafy wand and looks down at it.",
      "No crowd is present.",
    ],
    teachingLine: "The Page of Wands learns by trying, not by announcing a destiny.",
  }),
  makeCard({
    id: "wands-knight", name: "Knight of Wands", arcana, suit, rank: "knight",
    keywords: ["pursuit", "speed", "heat", "charge"],
    core: "This mode pursues at heat and often moves before the room has agreed. Sometimes that is how a stalled thing finally goes. Sometimes it is how a room burns.",
    gift: "You can use speed when the moment is actually short.",
    cost: "Speed that will not stay for the consequence leaves other people holding the scorch.",
    tilt: "excess",
    note: "Reversed, the charge is overdone. Motion substitutes for aim, and the pursuit cannot dismount. Heat is not a plan.",
    motifs: ["a rider leaning forward", "a raised wand", "dust and a restless horse"],
    imageCues: [
      "She leans forward on a galloping dark horse.",
      "She raises one wand, with fire at its tip.",
      "Dust rises under the horse's hooves.",
    ],
    teachingLine: "The Knight of Wands is pursuit that hates to wait.",
  }),
  makeCard({
    id: "wands-queen", name: "Queen of Wands", arcana, suit, rank: "queen",
    keywords: ["confidence", "presence", "warmth", "room"],
    core: "This mode inhabits confidence in a room it already understands. The warmth is practical. It is not a performance of being the sun.",
    gift: "You can hold attention without making the gathering about your shine.",
    cost: "Confidence that cannot hear a correction becomes a closed fire.",
    tilt: "inward",
    note: "Reversed, the presence turns inward and either hides or polices the room for signs of disloyalty. Warmth used as a test is not hospitality.",
    motifs: ["a seated figure with a sunflower or living wand", "a cat nearby", "a steady gaze outward"],
    imageCues: [
      "She sits in a high-backed chair holding a tall wand crowned by a sunflower.",
      "A cat sits on the arm of the chair beside her.",
      "She looks steadily outward.",
    ],
    teachingLine: "The Queen of Wands inhabits confidence without needing a stage.",
  }),
  makeCard({
    id: "wands-king", name: "King of Wands", arcana, suit, rank: "king",
    keywords: ["direction", "vision", "lead", "aim"],
    core: "This mode directs a vision other people can carry. The direction is a service. It is not proof that your heat outranks their judgment.",
    gift: "You can name an aim clearly enough that someone else can take a piece of it.",
    cost: "A vision that will not share the map turns allies into an audience.",
    tilt: "blocked",
    note: "Reversed, direction is blocked by charisma with no next step, or by a leader who will not be questioned. The salamander on the throne does not make the order wise.",
    motifs: ["a throne with a living wand", "a salamander or small lizard motif", "a forward-pointing posture"],
    imageCues: [
      "She sits on a throne and points forward with one hand.",
      "A leafy living wand rises beside the throne.",
      "A small lizard rests on the chair arm.",
    ],
    teachingLine: "The King of Wands directs a vision people can actually follow.",
  }),
];
