/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ReadRouteImport } from './routes/read'
import { Route as StudyRouteImport } from './routes/study'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'
import { Route as HistoryReadingIdRouteImport } from './routes/history.$readingId'
import { Route as StudyLessonIdRouteImport } from './routes/study.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryReadingIdRoute = HistoryReadingIdRouteImport.update({
  id: '/$readingId',
  path: '/$readingId',
  getParentRoute: () => HistoryRoute,
} as any)
const StudyLessonIdRoute = StudyLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => StudyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRouteWithChildren
  '/library': typeof LibraryRoute
  '/read': typeof ReadRoute
  '/study': typeof StudyRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/history/$readingId': typeof HistoryReadingIdRoute
  '/study/$lessonId': typeof StudyLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRouteWithChildren
  '/library': typeof LibraryRoute
  '/read': typeof ReadRoute
  '/study': typeof StudyRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/history/$readingId': typeof HistoryReadingIdRoute
  '/study/$lessonId': typeof StudyLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRouteWithChildren
  '/library': typeof LibraryRoute
  '/read': typeof ReadRoute
  '/study': typeof StudyRouteWithChildren
  '/card/$cardId': typeof CardCardIdRoute
  '/history/$readingId': typeof HistoryReadingIdRoute
  '/study/$lessonId': typeof StudyLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/history'
    | '/library'
    | '/read'
    | '/study'
    | '/card/$cardId'
    | '/history/$readingId'
    | '/study/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/library'
    | '/read'
    | '/study'
    | '/card/$cardId'
    | '/history/$readingId'
    | '/study/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/history'
    | '/library'
    | '/read'
    | '/study'
    | '/card/$cardId'
    | '/history/$readingId'
    | '/study/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  ReadRoute: typeof ReadRoute
  StudyRoute: typeof StudyRouteWithChildren
  CardCardIdRoute: typeof CardCardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$readingId': {
      id: '/history/$readingId'
      path: '/$readingId'
      fullPath: '/history/$readingId'
      preLoaderRoute: typeof HistoryReadingIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/study/$lessonId': {
      id: '/study/$lessonId'
      path: '/$lessonId'
      fullPath: '/study/$lessonId'
      preLoaderRoute: typeof StudyLessonIdRouteImport
      parentRoute: typeof StudyRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryReadingIdRoute: typeof HistoryReadingIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryReadingIdRoute: HistoryReadingIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface StudyRouteChildren {
  StudyLessonIdRoute: typeof StudyLessonIdRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyLessonIdRoute: StudyLessonIdRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LibraryRoute: LibraryRoute,
  ReadRoute: ReadRoute,
  StudyRoute: StudyRouteWithChildren,
  CardCardIdRoute: CardCardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
